---
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=8888"
        - "--response-text=http"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: example
spec:
  selector:
    app: http
  ports:
  - name: http
    port: 80
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--grpc-server-port=8888"
        - "--response-text=grpc"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: grpc
  namespace: example
spec:
  selector:
    app: grpc
  ports:
  - name: grpc
    port: 81
    targetPort: 8888    
